language: java
jdk:
  - openjdk14

# используем режим обычного пользователя для сборки проекта.
sudo: false

# Отправлять уведомление на почту если сборка упала
notifications:
  email:
    recipients:
      -sidelevcs@gmail.com
    on_success: never # default: change
    on_failure: always # default: always